let products=[
 {id:1,name:'Supreme PVC Pipe, 4 inch',category:'Pipes & Plumbing',price:615,unit:'per length',supplier:'SHARMA SANITARY · 1.2 KM',icon:'◯',color:'#dce9dc',tag:'IN STOCK'},
 {id:2,name:'Finolex Copper Wire, 1.5 sq mm',category:'Electrical',price:1240,unit:'per coil',supplier:'VOLTAGE ELECTRICALS · 2.1 KM',icon:'〰',color:'#f8df9e',tag:'FAST DELIVERY'},
 {id:3,name:'UltraTech Cement, 50 kg',category:'Cement & Concrete',price:395,unit:'per bag',supplier:'GUPTA BUILD MART · 0.8 KM',icon:'▰',color:'#cbd1d2',tag:'BEST PRICE'},
 {id:4,name:'Havells Modular Switch, 6A',category:'Electrical',price:88,unit:'per piece',supplier:'VOLTAGE ELECTRICALS · 2.1 KM',icon:'▣',color:'#f1e5d5',tag:'IN STOCK'},
 {id:5,name:'CPVC Elbow, 1 inch',category:'Pipes & Plumbing',price:52,unit:'per piece',supplier:'SHARMA SANITARY · 1.2 KM',icon:'⌐',color:'#dce9dc',tag:'IN STOCK'},
 {id:6,name:'TMT Steel Bar, 12 mm',category:'Cement & Concrete',price:708,unit:'per piece',supplier:'GUPTA BUILD MART · 0.8 KM',icon:'━',color:'#d7dfe1',tag:'TRADE RATE'},
 {id:7,name:'Insulated Safety Gloves',category:'Safety',price:310,unit:'per pair',supplier:'SAFE SITE HARDWARE · 1.5 KM',icon:'♧',color:'#f7d5c8',tag:'IN STOCK'},
 {id:8,name:'Heavy Duty Drill Machine',category:'Tools',price:2899,unit:'per piece',supplier:'SAFE SITE HARDWARE · 1.5 KM',icon:'⚒',color:'#dbdde1',tag:'FAST DELIVERY'}
];
let active='All',cart=[];
const grid=document.getElementById('productGrid');
async function loadProducts(){let q=document.getElementById('searchInput').value.toLowerCase();try{let response=await fetch(`/api/products?category=${encodeURIComponent(active)}&q=${encodeURIComponent(q)}`);if(!response.ok)throw Error();products=await response.json()}catch(e){products=[];showToast('Unable to load nearby inventory')}renderProducts()}
function renderProducts(){let list=products;grid.innerHTML=list.map(p=>`<article class="product"><div class="product-image" style="background:${p.color}"><span class="tag">${p.tag} · ${p.stock} LEFT</span><span class="shape">${p.icon}</span></div><div class="product-info"><span class="supplier">${p.supplier.toUpperCase()} · ${p.distance}</span><h3>${p.name}</h3><div class="price-row"><div class="price">₹${p.price.toLocaleString('en-IN')} <small>${p.unit}</small></div><button class="add" onclick="addToCart(${p.id})">+</button></div></div></article>`).join('')||'<p>No materials found nearby. Try a different search.</p>'}
function addToCart(id){let item=products.find(p=>p.id===id);let inCart=cart.find(x=>x.id===id);if(inCart)inCart.quantity++;else cart.push({...item,quantity:1});renderCart();showToast(item.name+' added to your order');}
function renderCart(){document.getElementById('cartCount').textContent=cart.reduce((n,p)=>n+p.quantity,0);let items=document.getElementById('cartItems');items.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><div class="mini-icon" style="background:${p.color}">${p.icon}</div><div><strong>${p.name} × ${p.quantity}</strong><span>₹${p.price.toLocaleString('en-IN')} · ${p.supplier}</span></div><button onclick="removeItem(${i})">×</button></div>`).join(''):'<p class="empty">Your material list is empty.</p>';document.getElementById('subtotal').textContent='₹'+cart.reduce((n,p)=>n+p.price*p.quantity,0).toLocaleString('en-IN')}
function removeItem(i){cart.splice(i,1);renderCart()}
function showToast(text){let t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{active=b.dataset.filter;document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');loadProducts()});
document.querySelectorAll('nav [data-category]').forEach(b=>b.onclick=()=>{active=b.dataset.category;document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.chips button').forEach(x=>x.classList.toggle('selected',x.dataset.filter===active));loadProducts();document.querySelector('.products').scrollIntoView({behavior:'smooth'})});
let searchTimer;document.getElementById('searchInput').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadProducts,250)};const panel=document.getElementById('cartPanel'),overlay=document.getElementById('overlay');function toggleCart(on){panel.classList.toggle('open',on);overlay.classList.toggle('show',on)}document.getElementById('cartButton').onclick=()=>toggleCart(true);document.getElementById('closeCart').onclick=()=>toggleCart(false);overlay.onclick=()=>toggleCart(false);document.getElementById('checkoutBtn').onclick=async()=>{if(!cart.length)return showToast('Add materials to continue');let button=document.getElementById('checkoutBtn');button.disabled=true;button.textContent='Creating order...';try{let response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart.map(p=>({id:p.id,quantity:p.quantity}))})});let order=await response.json();if(!response.ok)throw Error(order.error);cart=[];renderCart();toggleCart(false);showToast(`Order ${order.id} created successfully!`);loadProducts()}catch(e){showToast(e.message||'Could not create order')}finally{button.disabled=false;button.innerHTML='Proceed to checkout <b>→</b>'}};document.getElementById('matchBtn').onclick=()=>showToast('Finding verified suppliers near Sector 62...');document.getElementById('quoteBtn').onclick=()=>showToast('Bulk quote request form is opening soon.');document.getElementById('locationBtn').onclick=()=>showToast('Delivery location: Sector 62, Noida');document.getElementById('viewAll').onclick=()=>{active='All';loadProducts();showToast('Showing all nearby materials')};loadProducts();

// Account UI: customer and supplier onboarding
let authMode='register',authRole='customer',signedUser=JSON.parse(localStorage.getItem('buildkartUser')||'null');
const modal=document.getElementById('authModal');
function updateAccount(){document.getElementById('accountBtn').innerHTML=signedUser?`${signedUser.name.split(' ')[0]} <span>⌄</span>`:'Sign in <span>↗</span>'}
function renderAuth(){let login=authMode==='login';document.getElementById('authTitle').textContent=login?'Sign in to your account':'Create your account';document.getElementById('authCopy').textContent=authRole==='supplier'?'Manage your stock and receive construction orders.':'Order material and track delivery to your site.';document.getElementById('nameLabel').style.display=login?'none':'block';document.getElementById('authSubmit').innerHTML=(login?'Sign in':'Create account')+' <b>→</b>';document.getElementById('toggleText').textContent=login?'New to BuildKart?':'Already have an account?';document.getElementById('toggleAuth').textContent=login?'Create account':'Sign in'}
document.getElementById('accountBtn').onclick=()=>{if(signedUser)return showToast(`Signed in as ${signedUser.role}`);modal.classList.add('show')};document.getElementById('closeAuth').onclick=()=>modal.classList.remove('show');document.getElementById('toggleAuth').onclick=()=>{authMode=authMode==='login'?'register':'login';renderAuth()};document.querySelectorAll('.role').forEach(b=>b.onclick=()=>{authRole=b.dataset.role;document.querySelectorAll('.role').forEach(x=>x.classList.toggle('active',x===b));renderAuth()});document.getElementById('authSubmit').onclick=()=>{let name=document.getElementById('authName').value.trim(),email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||password.length<6||(!name&&authMode==='register'))return showToast('Please enter valid account details');signedUser={name:name||email.split('@')[0],email,role:authRole};localStorage.setItem('buildkartUser',JSON.stringify(signedUser));updateAccount();modal.classList.remove('show');showToast(`Welcome, ${signedUser.name}!`)};updateAccount();renderAuth();
function showSupplierDashboard(){if(document.getElementById('supplierDashboard'))return;document.querySelector('nav').style.display='none';document.querySelector('main').style.display='none';document.querySelector('footer').style.display='none';let dash=document.createElement('section');dash.id='supplierDashboard';dash.className='supplier-dashboard';dash.innerHTML=`<div class="dash-top"><div><p class="eyebrow">SUPPLIER PORTAL</p><h1>Good morning, ${signedUser.name}.</h1><p>Manage your local store orders and inventory from one place.</p></div><span class="dashboard-tag">SUPPLIER ACCOUNT</span></div><div class="dash-stats"><div class="dash-stat"><span>NEW ORDERS</span><strong>03</strong></div><div class="dash-stat"><span>ITEMS IN STOCK</span><strong>551</strong></div><div class="dash-stat"><span>THIS WEEK’S SALES</span><strong>₹24,680</strong></div></div><div class="supplier-table"><h2>New material requests</h2><div class="order-row head"><span>ORDER</span><span>MATERIAL</span><span>AMOUNT</span><span>STATUS</span></div><div class="order-row"><span><b>#BK-8392142</b><br><small>Sector 62, Noida</small></span><span>UltraTech Cement × 30</span><span>₹11,850</span><span class="status">ACTION NEEDED</span></div><div class="order-row"><span><b>#BK-8392136</b><br><small>Sector 58, Noida</small></span><span>PVC Pipe × 12</span><span>₹7,380</span><span class="status">ACTION NEEDED</span></div></div><button class="switch-view" id="customerView">← View customer storefront</button>`;document.body.insertBefore(dash,document.querySelector('.cart-panel'));document.getElementById('customerView').onclick=()=>{dash.remove();document.querySelector('nav').style.display='flex';document.querySelector('main').style.display='block';document.querySelector('footer').style.display='flex'}}
document.getElementById('authSubmit').onclick=()=>{let name=document.getElementById('authName').value.trim(),email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||password.length<6||(!name&&authMode==='register'))return showToast('Please enter valid account details');signedUser={name:name||email.split('@')[0],email,role:authRole};localStorage.setItem('buildkartUser',JSON.stringify(signedUser));updateAccount();modal.classList.remove('show');showToast(`Welcome, ${signedUser.name}!`);if(signedUser.role==='supplier')showSupplierDashboard()};if(signedUser?.role==='supplier')showSupplierDashboard();
